### ISSUE TITLE
Ansible failed to complete successfully "module: warn"

### ISSUE THREAD

**Issue by hawbirr** [RIPE-NCC/bgp-security-lab#3]
hello guys,

while I was trying to install and run the lab, I come cross the below error. 
I had to remove "warn: false" on both line 50 and 367 from /bgp-security-lab/ansible/site.yaml
then I was enable to complete the installation.

TASK [Install python3-apt] *****************************************************
fatal: [default -> server]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: _raw_params, _uses_shell, argv, chdir, creates, executable, removes, stdin, stdin_add_newline, strip_empty_ends."}

PLAY RECAP *********************************************************************
default                    : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

![image](https://user-images.githubusercontent.com/72047317/218827068-f3b73d5f-9198-47ba-8e2a-0c820f481ca6.png)

since I haven't run the lab totally to do the tasks, I don't know if it cause an issue or not ?
please let us know if it's ok ? or what is the solution for it?

Thank you.

**Comment by oskar456** [comment]
Thank you for the report. This is indeed a change in the latest ansible. I have removed the `warn: true` parameters from the playbook. This is the proper solution to the problem and the lab environment should work normally.
